export const SELECTED_CHILD = 'SELECTED_CHILD';
export const FETCH_CHILDREN_SUCCESS = 'FETCH_CHILDREN_SUCCESS';
export const SEARCH_CHILD_REQUEST = 'SEARCH_CHILD_REQUEST';
export const SEARCH_CHILD_SUCCESS = 'SEARCH_CHILD_SUCCESS';
export const SEARCH_CHILD_FAILURE = 'SEARCH_CHILD_FAILURE';
export const CHECKIN_CHILD = 'CHECKIN_CHILD';
export const CHECKOUT_CHILD = 'CHECKOUT_CHILD';
